// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_download_id_ from "./routes/api/download/[id].ts";
import * as $api_match from "./routes/api/match.ts";
import * as $api_upload from "./routes/api/upload.ts";
import * as $index from "./routes/index.tsx";
import * as $AlgorithmSelector from "./islands/AlgorithmSelector.tsx";
import * as $FileUploadZone from "./islands/FileUploadZone.tsx";
import * as $LoadingSpinner from "./islands/LoadingSpinner.tsx";
import * as $ProgressBar from "./islands/ProgressBar.tsx";
import * as $ThemeProvider from "./islands/ThemeProvider.tsx";
import * as $Toast from "./islands/Toast.tsx";
import * as $UploadForm from "./islands/UploadForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/download/[id].ts": $api_download_id_,
    "./routes/api/match.ts": $api_match,
    "./routes/api/upload.ts": $api_upload,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AlgorithmSelector.tsx": $AlgorithmSelector,
    "./islands/FileUploadZone.tsx": $FileUploadZone,
    "./islands/LoadingSpinner.tsx": $LoadingSpinner,
    "./islands/ProgressBar.tsx": $ProgressBar,
    "./islands/ThemeProvider.tsx": $ThemeProvider,
    "./islands/Toast.tsx": $Toast,
    "./islands/UploadForm.tsx": $UploadForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
